services:
  db:
    image: postgres:latest
    container_name: secure-postgres
    environment:
      POSTGRES_USER: secure_user  
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: secure_DB
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080" 

volumes:
  pgdata: